name: ClientBan
version: 1.0.0
author: applqpak
api:
- 1.0.0
- 2.0.0
main: ClientBan\Main
commands:
  clientban:
    usage: "/clientban <player> < reason >"
    description: Ban A Players UUID.
    permission: clientban.command
    alias: [cban, cb]
  clientpardon:
    usage: "/clientpardon <player>"
    description: Unban A Players UUID.
    permission: clientpardon.command
    alias: [cpardon, cp]
  clientbanlist:
    usage: "/clientbanlist"
    description: Check The Ban Lsot Of Player UUIDS.
    permission: clientbanlist.command
    alias: [cbanlist, cbl]
permissions:
  clientban.command:
    default: op
  clientpardon.commamd:
    default: op
  clientbanlist.command:
    default: op
