name: ClientBan
version: 1.0.0
author: applqpak
api:
- 1.0.0
- 2.0.0
main: ClientBan\Main
commands:
  clientban:
    usage: "/clientban <player> < reason >"
    description: Ban A Players UUID.
    permission: clientban.command
permissions:
  clientban.command:
    default: op
